/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/categories`; params?: Router.UnknownInputParams; } | { pathname: `/explore-details`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/marketDetails`; params?: Router.UnknownInputParams; } | { pathname: `/notifications`; params?: Router.UnknownInputParams; } | { pathname: `/signUp`; params?: Router.UnknownInputParams; } | { pathname: `/../components/common/floating-tab-bar`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/settings/about`; params?: Router.UnknownInputParams; } | { pathname: `/settings/app-settings`; params?: Router.UnknownInputParams; } | { pathname: `/settings/edit-profile`; params?: Router.UnknownInputParams; } | { pathname: `/settings/notifications`; params?: Router.UnknownInputParams; } | { pathname: `/settings/security`; params?: Router.UnknownInputParams; } | { pathname: `/settings/support`; params?: Router.UnknownInputParams; } | { pathname: `/tabs/explore`; params?: Router.UnknownInputParams; } | { pathname: `/tabs/home`; params?: Router.UnknownInputParams; } | { pathname: `/tabs/leaderboard`; params?: Router.UnknownInputParams; } | { pathname: `/tabs/profile`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/categories`; params?: Router.UnknownOutputParams; } | { pathname: `/explore-details`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/login`; params?: Router.UnknownOutputParams; } | { pathname: `/marketDetails`; params?: Router.UnknownOutputParams; } | { pathname: `/notifications`; params?: Router.UnknownOutputParams; } | { pathname: `/signUp`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/common/floating-tab-bar`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/settings/about`; params?: Router.UnknownOutputParams; } | { pathname: `/settings/app-settings`; params?: Router.UnknownOutputParams; } | { pathname: `/settings/edit-profile`; params?: Router.UnknownOutputParams; } | { pathname: `/settings/notifications`; params?: Router.UnknownOutputParams; } | { pathname: `/settings/security`; params?: Router.UnknownOutputParams; } | { pathname: `/settings/support`; params?: Router.UnknownOutputParams; } | { pathname: `/tabs/explore`; params?: Router.UnknownOutputParams; } | { pathname: `/tabs/home`; params?: Router.UnknownOutputParams; } | { pathname: `/tabs/leaderboard`; params?: Router.UnknownOutputParams; } | { pathname: `/tabs/profile`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/categories${`?${string}` | `#${string}` | ''}` | `/explore-details${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `/marketDetails${`?${string}` | `#${string}` | ''}` | `/notifications${`?${string}` | `#${string}` | ''}` | `/signUp${`?${string}` | `#${string}` | ''}` | `/../components/common/floating-tab-bar${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/settings/about${`?${string}` | `#${string}` | ''}` | `/settings/app-settings${`?${string}` | `#${string}` | ''}` | `/settings/edit-profile${`?${string}` | `#${string}` | ''}` | `/settings/notifications${`?${string}` | `#${string}` | ''}` | `/settings/security${`?${string}` | `#${string}` | ''}` | `/settings/support${`?${string}` | `#${string}` | ''}` | `/tabs/explore${`?${string}` | `#${string}` | ''}` | `/tabs/home${`?${string}` | `#${string}` | ''}` | `/tabs/leaderboard${`?${string}` | `#${string}` | ''}` | `/tabs/profile${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/categories`; params?: Router.UnknownInputParams; } | { pathname: `/explore-details`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/marketDetails`; params?: Router.UnknownInputParams; } | { pathname: `/notifications`; params?: Router.UnknownInputParams; } | { pathname: `/signUp`; params?: Router.UnknownInputParams; } | { pathname: `/../components/common/floating-tab-bar`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/settings/about`; params?: Router.UnknownInputParams; } | { pathname: `/settings/app-settings`; params?: Router.UnknownInputParams; } | { pathname: `/settings/edit-profile`; params?: Router.UnknownInputParams; } | { pathname: `/settings/notifications`; params?: Router.UnknownInputParams; } | { pathname: `/settings/security`; params?: Router.UnknownInputParams; } | { pathname: `/settings/support`; params?: Router.UnknownInputParams; } | { pathname: `/tabs/explore`; params?: Router.UnknownInputParams; } | { pathname: `/tabs/home`; params?: Router.UnknownInputParams; } | { pathname: `/tabs/leaderboard`; params?: Router.UnknownInputParams; } | { pathname: `/tabs/profile`; params?: Router.UnknownInputParams; };
    }
  }
}
